//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.ResearchAuthors = new HashSet<ResearchAuthor>();
        }
    
        public int authorID { get; set; }
        public string title { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> schoolID { get; set; }
        public Nullable<int> telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> mobile { get; set; }
        public string university { get; set; }
        public string campus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchAuthor> ResearchAuthors { get; set; }
        public virtual School School { get; set; }
    }
}
