//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int recordID { get; set; }
        public int researchID { get; set; }
        public string fileID { get; set; }
    
        public virtual Research Research { get; set; }
    }
}
