//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public class ResearchAuthor
    {

        
        [ForeignKey("Research")]
        public int researchID { get; set; }

        [ForeignKey("Author")]
        public int authorID { get; set; }
    
        public virtual ICollection<Author> Author { get; set; }
        public virtual Research Research { get; set; }
    }
}
