//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Research
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Research()
        {
            this.Records = new HashSet<Record>();
            this.ResearchAuthors = new HashSet<ResearchAuthor>();
        }
    
        public int researchID { get; set; }
        public string title { get; set; }
        public Nullable<int> schoolID { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
        public string subject { get; set; }
        public Nullable<double> grants { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> downloads { get; set; }
        public string @abstract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchAuthor> ResearchAuthors { get; set; }
        public virtual School School { get; set; }
    }
}
