//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public  class School
    {
    
        public int schoolID { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name="School Name")]
        public string schoolName { get; set; }

        [StringLength(50)]
        [Display(Name = "Discipline Name")]
        public string disciplineName { get; set; }
    
       
        public virtual ICollection<Research> Researches { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
